### ISSUE TITLE
Facebook API version & Coldbox-ification

### ISSUE THREAD

**Issue by DiscountDarcy** [mjclemente/fbccfml#1]
Hiya Matt,

Kudos for doing this - had a client ask for an FBC implementation yesterday on short notice and didn't expect to find much on forgebox for it.

Just two questions:

1) I see the default Facebook graph API version is 10. It looks like their current version is 12. Do you happen to know if your CFC will do v12 (not that it makes a big difference, apparently) and if not, what kind of lift is required? If it's not much, we may just do it and get you a PR. I haven't worked with the API before but it looks pretty straightforward.

2) Any objections to our adding a ModuleConfig.cfc PR that binds facebookconversions.cfc as a sinlgeton? It looks like you did this for a non-Coldbox app and it's easy enough to use, but if we get in to hacking it anyway, we may as well mainline it into Coldbox. Without making that required, obviously.

Thanks again!

**Comment by mjclemente** [comment]
Glad it looks useful to you!

1. I'm not sure, but I think it should work with 12. I'll see if I can track down if anything has changed.
2. No objections at all.

Cheers!

**Comment by mjclemente** [comment]
Just leaving this here so that I can come back and look over the release notes when I have a minute: https://developers.facebook.com/docs/graph-api/changelog/version12.0

**Comment by DiscountDarcy** [comment]
FWIW, I changed the api default version to 12 and it "just worked."
